version: '3.8'

services:
  badword-detector:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./custom_bad_words.json:/app/custom_bad_words.json
      - model_cache:/app/.cache
    environment:
      - PYTHONUNBUFFERED=1
      - TRANSFORMERS_CACHE=/app/.cache/transformers
      - TORCH_HOME=/app/.cache/torch
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  model_cache: 